---
title: "CDS - Assignment 4"
author: "Jakub Raszka"
date: "5 10 2020"
output: word_document
---



## exercise
```{r}


## when changing wd, do it OUTSIDE of SETUP CHUNK!!!
knitr::opts_knit$set(root.dir = "C:/Users/Kuba/Dokumenter/CDS_class")
setwd("~/CDS_class")
# loading tidyverse
pacman::p_load(tidyverse)

## downloading data into a raw_data folder
#download.file("https://ndownloader.figshare.com/files/11492171", "raw_data/SAFI_clean.csv", mode = "wb")

interviews <- read_csv("raw_data/SAFI_clean.csv", na = "NULL")

interviews100 <- interviews[100,]

interviews[round(nrow(interviews)/2),]

interviews %>% 
  filter(!is.na(memb_assoc))


interviews %>% 
  group_by(village) %>% 
  summarize(mean_no_membr = mean(no_membrs))


interviews_plotting <- interviews %>%
  ## pivot wider by items_owned
  separate_rows(items_owned, sep = ";") %>%
  ## if there were no items listed, changing NA to no_listed_items
  replace_na(list(items_owned = "no_listed_items")) %>%
  mutate(items_owned_logical = TRUE) %>%
  pivot_wider(names_from = items_owned, 
              values_from = items_owned_logical, 
              values_fill = list(items_owned_logical = FALSE)) %>%
  ## pivot wider by months_lack_food
  separate_rows(months_lack_food, sep = ";") %>%
  mutate(months_lack_food_logical = TRUE) %>%
  pivot_wider(names_from = months_lack_food, 
              values_from = months_lack_food_logical, 
              values_fill = list(months_lack_food_logical = FALSE)) %>%
  ## add some summary columns
  mutate(number_months_lack_food = rowSums(select(., Jan:May))) %>%
  mutate(number_items = rowSums(select(., bicycle:car)))

write_csv(interviews_plotting, "interviews_plotting.csv")
```


## ggploting
```{r}
interviews_plotting %>% 
  ggplot(aes(x = no_membrs, y = number_items)) + 
  geom_jitter(aes(color = village), alpha = 1)


```




